export const HTTP_STATUS_OK = 200

export const HTTP_STATUS_CREATED = 201

export const HTTP_STATUS_BAD_REQUEST = 400

export const HTTP_STATUS_NOT_FOUND = 404

export const HTTP_STATUS_SERVER_ERROR = 500